[package]
name = "hl7-parser"
authors = ["Kenton Hamaluik <kenton@hamaluik.ca>"]
version = "0.0.1"
edition = "2021"

[dependencies]
nom = "7"
nom_locate = "4"
time = "0.3"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "parse_benchmark"
harness = false
