name: Test + Build Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set Timezone
      run: sudo timedatectl set-timezone America/Edmonton
    - name: Setup toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Run tests
      run: cargo test --verbose --all-features

